name: 'Serverless Action'
description: Github action for serverless framework
inputs:
  stage:
    description: severless app stage
    default: dev
  args:
    description: arguments for sls command
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
    - ${{ inputs.stage}}
branding:
  icon: 'zap' 
  color: black
